#!/bin/bash

echo "🔧 Configurando NocoDB para Cotizador Solar"
echo "============================================="

# Variables de entorno para NocoDB
echo "📋 Variables de entorno necesarias:"
echo ""
echo "# NocoDB Configuration"
echo "NOCODB_URL=https://bots-nocodb.prskfv.easypanel.host"
echo "NOCODB_TOKEN=JvshcwW9JUK_sR4yT7H5r7ygSA2BPFAGNI8nSeWF"
echo "NOCODB_BASE_ID=pjo0a1kfnvm1ai3"
echo ""
echo "# Tabla de Contactos"
echo "NOCODB_CONTACTOS_TABLE_ID=m7i75nx5rkwockg"
echo "NOCODB_CONTACTOS_ID_COLUMN=id"
echo "NOCODB_CONTACTOS_NOMBRE_COLUMN=nombre_cliente"
echo "NOCODB_CONTACTOS_EMAIL_COLUMN=email_cliente"
echo "NOCODB_CONTACTOS_TELEFONO_COLUMN=telefono_cliente"
echo "NOCODB_CONTACTOS_MENSAJE_COLUMN=mensaje_consulta"
echo "NOCODB_CONTACTOS_FECHA_COLUMN=fecha_consulta"
echo "NOCODB_CONTACTOS_ESTADO_COLUMN=estado_consulta"
echo "NOCODB_CONTACTOS_ORIGEN_COLUMN=origen_consulta"
echo "NOCODB_CONTACTOS_NOTAS_COLUMN=notas_internas"
echo ""
echo "# Tabla de Cotizaciones Solares"
echo "NOCODB_COTIZACIONES_TABLE_ID=cotizaciones_solares_table_id"
echo "NOCODB_COTIZACIONES_ID_COLUMN=id"
echo "NOCODB_COTIZACIONES_CLIENTE_ID_COLUMN=cliente_id"
echo "NOCODB_COTIZACIONES_NOMBRE_COLUMN=nombre_cliente"
echo "NOCODB_COTIZACIONES_EMAIL_COLUMN=email_cliente"
echo "NOCODB_COTIZACIONES_UBICACION_COLUMN=ubicacion_proyecto"
echo "NOCODB_COTIZACIONES_CONSUMO_COLUMN=consumo_mensual_kwh"
echo "NOCODB_COTIZACIONES_TARIFA_COLUMN=tipo_tarifa"
echo "NOCODB_COTIZACIONES_AREA_COLUMN=area_disponible_m2"
echo "NOCODB_COTIZACIONES_INSTALACION_COLUMN=tipo_instalacion"
echo "NOCODB_COTIZACIONES_POTENCIA_COLUMN=potencia_requerida_kwp"
echo "NOCODB_COTIZACIONES_PANELES_COLUMN=cantidad_paneles"
echo "NOCODB_COTIZACIONES_GENERACION_COLUMN=generacion_mensual_kwh"
echo "NOCODB_COTIZACIONES_AHORRO_COLUMN=ahorro_mensual_ars"
echo "NOCODB_COTIZACIONES_INVERSION_COLUMN=inversion_total_ars"
echo "NOCODB_COTIZACIONES_RETORNO_COLUMN=retorno_inversion_anos"
echo "NOCODB_COTIZACIONES_ESTADO_COLUMN=estado_cotizacion"
echo "NOCODB_COTIZACIONES_FECHA_CREACION_COLUMN=fecha_creacion"
echo "NOCODB_COTIZACIONES_VALIDA_HASTA_COLUMN=valida_hasta"
echo "NOCODB_COTIZACIONES_NOTAS_COLUMN=notas_proyecto"
echo "NOCODB_COTIZACIONES_PDF_COLUMN=archivo_pdf"
echo ""
echo "# Tabla de Materiales Solares"
echo "NOCODB_MATERIALES_TABLE_ID=materiales_solares_table_id"
echo "NOCODB_MATERIALES_ID_COLUMN=id"
echo "NOCODB_MATERIALES_TIPO_COLUMN=tipo_material"
echo "NOCODB_MATERIALES_MARCA_COLUMN=marca"
echo "NOCODB_MATERIALES_MODELO_COLUMN=modelo"
echo "NOCODB_MATERIALES_POTENCIA_WATTS_COLUMN=potencia_watts"
echo "NOCODB_MATERIALES_POTENCIA_KW_COLUMN=potencia_kw"
echo "NOCODB_MATERIALES_PRECIO_ARS_COLUMN=precio_ars"
echo "NOCODB_MATERIALES_PRECIO_POR_KW_COLUMN=precio_por_kw"
echo "NOCODB_MATERIALES_STOCK_COLUMN=stock_disponible"
echo "NOCODB_MATERIALES_ACTIVO_COLUMN=activo"
echo "NOCODB_MATERIALES_ESPECIFICACIONES_COLUMN=especificaciones_tecnicas"
echo "NOCODB_MATERIALES_GARANTIA_COLUMN=garantia_anos"
echo "NOCODB_MATERIALES_PROVEEDOR_COLUMN=proveedor"
echo "NOCODB_MATERIALES_FECHA_ACTUALIZACION_COLUMN=fecha_actualizacion"
echo ""
echo "# Tabla de Logs del Sistema"
echo "NOCODB_LOGS_TABLE_ID=logs_sistema_table_id"
echo "NOCODB_LOGS_ID_COLUMN=id"
echo "NOCODB_LOGS_TIPO_EVENTO_COLUMN=tipo_evento"
echo "NOCODB_LOGS_MENSAJE_COLUMN=mensaje"
echo "NOCODB_LOGS_NIVEL_COLUMN=nivel_log"
echo "NOCODB_LOGS_USUARIO_COLUMN=usuario"
echo "NOCODB_LOGS_IP_COLUMN=ip_cliente"
echo "NOCODB_LOGS_FECHA_COLUMN=fecha_hora"
echo "NOCODB_LOGS_DATOS_COLUMN=datos_adicionales"
echo ""
echo "📁 Archivos creados:"
echo "- contactos.csv (datos de contactos)"
echo "- cotizaciones_solares.csv (datos de cotizaciones)"
echo "- materiales_solares.csv (catálogo de materiales)"
echo "- logs_sistema.csv (logs del sistema)"
echo "- nocodb-columns-config.json (configuración detallada)"
echo "- setup-nocodb.sh (este script)"
echo ""
echo "🚀 Pasos siguientes:"
echo "1. Importa cada archivo CSV a NocoDB como tabla separada"
echo "2. NocoDB detectará automáticamente los tipos de datos"
echo "3. Obtén los TABLE_ID de cada tabla creada"
echo "4. Actualiza las variables de entorno con los TABLE_ID reales"
echo "5. Reinicia la aplicación"
echo ""
echo "📋 Tablas a crear:"
echo "- contactos (formularios de contacto)"
echo "- cotizaciones_solares (cotizaciones generadas)"
echo "- materiales_solares (catálogo de productos)"
echo "- logs_sistema (logs de la aplicación)"
echo ""
echo "✅ Configuración completada!"
